trailingComma: 'es5'
tabWidth: 4
useTabs: false
semi: false
singleQuote: true
quoteProps: 'consistent'
printWidth: 120
arrowParens: 'avoid'
bracketSpacing: true
bracketSameLine: false

# npx prettier . --write